name = "Better MC [FABRIC] BMC3"
author = "LunaPixelStudios"
version = "v14.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea97c0a5aa777390acbdec9e67444396b795d78c09dcfd73d97bfe8e0550c918"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
